# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  Repo_Name: ${{ github.event.repository.name }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11.
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Repo Name
      run: |
          echo "${{ env.Repo_Name}}"
    - name: Display Date
      id: date
      run: |
          echo "::set-output name=date::$(date +'%m-%d-%Y %H:%M:%S')"
    - name: Date
      env: 
        GithubDate: ${{ steps.date.outputs.date }}
      run: |
          echo "${{ env.GithubDate}}"
    - name: Get Github Token
      run : |
           echo "${{ secrets.GITHUB_TOKEN }}"
    - name: Build with Maven
      run: |
          mvn -B package --file pom.xml
          #ls /home/runner/work/cds-javaJson/cds-javaJson/target/
          #ls -la  ls /home/runner/work/cds-javaJson/cds-javaJson/target/surefire-reports
      
    - name: 'Publish JAR'
      uses: actions/upload-artifact@v2-preview
      with:
          name: ‘cicd-demo-${{env.VERSION}}-all.jar'
          path: demo.jar
    - name: Run Java
      run: |
          ls /home/runner/work/cds-javaJson/cds-javaJson/target/
          java -jar demo.jar
    - name: 'Publish JSON'
      uses: actions/upload-artifact@v2-preview
      with:
          name: 'test-results.json'
          path: /home/runner/work/cds-javaJson/cds-javaJson/cds-GithubActionIntegration.json
    - name: 'Run Script'
      run: |
         python json-script.py --auth ${{ secrets.GITHUB_TOKEN }} --repo_name ${{ env.Repo_Name}}
          
 
          
