# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  Repo_Name: ${{ github.event.repository.name }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Repo Name
      run: |
          echo "${{ env.Repo_Name}}"
    - name: Display Date
      id: date
      run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
      env: 
        GithubDate: ${{ steps.date.outputs.date }}
    - name: Date
      run: |
          echo "${{ env.GithubDate}}"
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: 'Publish JAR'
      uses: actions/upload-artifact@v2-preview
      with:
          name: ‘cicd-demo-${{env.VERSION}}-all.jar'
          path: demo.jar
 
          
